version: "3.1"

networks:
  net1:

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: asynchw
    ports:
      - "5430:5432"
    networks:
      net1:
        aliases:
          - database